-- Categories for RUBiS database
-- This file has been automatically generated by generate_categories.awk script usingas input file

INSERT INTO categories VALUES (NULL,'Antiques & Art ');
INSERT INTO categories VALUES (NULL,'Books ');
INSERT INTO categories VALUES (NULL,'Business, Office & Industrial ');
INSERT INTO categories VALUES (NULL,'Clothing & Accessories ');
INSERT INTO categories VALUES (NULL,'Coins ');
INSERT INTO categories VALUES (NULL,'Collectibles ');
INSERT INTO categories VALUES (NULL,'Computers ');
INSERT INTO categories VALUES (NULL,'Consumer Electronics ');
INSERT INTO categories VALUES (NULL,'Dolls & Bears ');
INSERT INTO categories VALUES (NULL,'Home & Garden ');
INSERT INTO categories VALUES (NULL,'Jewelry, Gems & Watches ');
INSERT INTO categories VALUES (NULL,'Movies & Television ');
INSERT INTO categories VALUES (NULL,'Music ');
INSERT INTO categories VALUES (NULL,'Photo ');
INSERT INTO categories VALUES (NULL,'Pottery & Glass ');
INSERT INTO categories VALUES (NULL,'Sports ');
INSERT INTO categories VALUES (NULL,'Stamps ');
INSERT INTO categories VALUES (NULL,'Tickets & Travel ');
INSERT INTO categories VALUES (NULL,'Toys & Hobbies ');
INSERT INTO categories VALUES (NULL,'Everything Else ');
