#!/bin/awk -f

BEGIN {
  SQLoutput = "regions.sql";
  print "# Regions for RUBiS database" > SQLoutput;
  print "# This file has been automatically generated by generate_regions.awk script using" FILENAME "as input file\n" > SQLoutput;
}
{
  print "INSERT INTO regions VALUES (NULL,'" $0 "');" > SQLoutput;
}
