USE rubis;

DROP TABLE IF EXISTS categories;

DROP TABLE IF EXISTS regions;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS items;

DROP TABLE IF EXISTS old_items;

DROP TABLE IF EXISTS bids;

DROP TABLE IF EXISTS comments;

DROP TABLE IF EXISTS buy_now;

DROP TABLE IF EXISTS ids;
